import Foundation
import Supabase
final class SupabaseVenueRepository:VenueRepository,@unchecked Sendable{private let provider:SupabaseProvider;private let columns="id,wedding_id,name,status,location,location_text,address,city,state,country,contact_name,contact_email,contact_phone,website,capacity_min,capacity_max,capacity_text,price_estimate,price_notes,venue_est_text,all_in_est_text,available_dates_text,notes,our_notes,summary,latitude,longitude,photo_url,raw_research,created_at,updated_at";private let photoColumns="id,venue_id,wedding_id,url,source,caption,sort_order,created_at";init(provider:SupabaseProvider){self.provider=provider}
func venues(weddingID:UUID)async throws->[Venue]{try await run{try await self.provider.client.from("venues").select(self.columns).eq("wedding_id",value:DomainRepositorySupport.uuid(weddingID)).neq("status",value:"suggested").order("created_at",ascending:false).execute().value}}
func createVenue(_ draft:VenueDraft,weddingID:UUID)async throws->Venue{try await run{try await self.provider.client.from("venues").insert(VenueCreate(weddingID:weddingID,draft:draft)).select(self.columns).single().execute().value}}
func updateVenue(id:UUID,patch:VenuePatch)async throws->Venue{try DomainRepositorySupport.requirePatch(patch.isEmpty,"Venue update must include at least one field.");return try await run{try await self.provider.client.from("venues").update(patch).eq("id",value:DomainRepositorySupport.uuid(id)).select(self.columns).single().execute().value}}
func deleteVenue(id:UUID)async throws{let _:VenueDeleteReceipt=try await run{try await self.provider.client.from("venues").delete().eq("id",value:DomainRepositorySupport.uuid(id)).select("id").single().execute().value}}
func venuePhotos(venueID:UUID)async throws->[VenuePhoto]{try await run{try await self.provider.client.from("venue_photos").select(self.photoColumns).eq("venue_id",value:DomainRepositorySupport.uuid(venueID)).order("sort_order",ascending:true,nullsFirst:false).execute().value}}
func createVenuePhoto(_ draft:VenuePhotoDraft,venueID:UUID,weddingID:UUID)async throws->VenuePhoto{try await run{try await self.provider.client.from("venue_photos").insert(VenuePhotoCreate(venueID:venueID,weddingID:weddingID,draft:draft)).select(self.photoColumns).single().execute().value}}
func updateVenuePhoto(id:UUID,patch:VenuePhotoPatch)async throws->VenuePhoto{try DomainRepositorySupport.requirePatch(patch.isEmpty,"Venue photo update must include at least one field.");return try await run{try await self.provider.client.from("venue_photos").update(patch).eq("id",value:DomainRepositorySupport.uuid(id)).select(self.photoColumns).single().execute().value}}
func deleteVenuePhoto(id:UUID)async throws{let _:VenueDeleteReceipt=try await run{try await self.provider.client.from("venue_photos").delete().eq("id",value:DomainRepositorySupport.uuid(id)).select("id").single().execute().value}}
private func run<T:Decodable & Sendable>(_ body:()async throws->T)async throws->T{do{try await DomainRepositorySupport.authenticated(provider);return try await body()}catch{throw DomainRepositorySupport.normalized(error,fallback:"Venue request failed.")}}}
private struct VenueCreate:Codable{let weddingID:UUID;let name:String;let status:VenueStatus?;let location:String?;let address:String?;let city:String?;let state:String?;let country:String?;let contactName:String?;let contactEmail:String?;let contactPhone:String?;let website:String?;let capacityMin:Int?;let capacityMax:Int?;let priceEstimate:Double?;let priceNotes:String?;let notes:String?;let latitude:Double?;let longitude:Double?;let photoURL:String?;init(weddingID:UUID,draft:VenueDraft){self.weddingID=weddingID;name=draft.name;status=draft.status;location=draft.location;address=draft.address;city=draft.city;state=draft.state;country=draft.country;contactName=draft.contactName;contactEmail=draft.contactEmail;contactPhone=draft.contactPhone;website=draft.website;capacityMin=draft.capacityMin;capacityMax=draft.capacityMax;priceEstimate=draft.priceEstimate;priceNotes=draft.priceNotes;notes=draft.notes;latitude=draft.latitude;longitude=draft.longitude;photoURL=draft.photoURL};enum CodingKeys:String,CodingKey{case weddingID="wedding_id";case name;case status;case location;case address;case city;case state;case country;case contactName="contact_name";case contactEmail="contact_email";case contactPhone="contact_phone";case website;case capacityMin="capacity_min";case capacityMax="capacity_max";case priceEstimate="price_estimate";case priceNotes="price_notes";case notes;case latitude;case longitude;case photoURL="photo_url"}}
private struct VenuePhotoCreate:Codable{let venueID:UUID;let weddingID:UUID;let url:String;let source:String?;let caption:String?;let sortOrder:Int?;init(venueID:UUID,weddingID:UUID,draft:VenuePhotoDraft){self.venueID=venueID;self.weddingID=weddingID;url=draft.url;source=draft.source;caption=draft.caption;sortOrder=draft.sortOrder};enum CodingKeys:String,CodingKey{case venueID="venue_id";case weddingID="wedding_id";case url;case source;case caption;case sortOrder="sort_order"}}
private struct VenueDeleteReceipt:Decodable,Sendable{let id:UUID}
