import Foundation
import Supabase
final class SupabaseVenueRepository:VenueRepository,@unchecked Sendable{private let provider:SupabaseProvider;private let columns="id,wedding_id,name,status,address,city,state,country,contact_name,contact_email,contact_phone,website,capacity_min,capacity_max,capacity_text,price_notes,venue_est_text,all_in_est_text,available_dates_text,our_notes,summary,latitude,longitude,photo_url,custom_fields,created_at,updated_at";private let customColumnColumns="id,wedding_id,key,label,kind,options,position,hidden,created_at,updated_at";private let photoColumns="id,venue_id,wedding_id,url,source,caption,sort_order,created_at";init(provider:SupabaseProvider){self.provider=provider}
func venues(weddingID:UUID)async throws->[Venue]{try await run{try await self.provider.client.from("venues").select(self.columns).eq("wedding_id",value:DomainRepositorySupport.uuid(weddingID)).order("created_at",ascending:false).execute().value}}
func createVenue(_ draft:VenueDraft,weddingID:UUID)async throws->Venue{try await run{try await self.provider.client.from("venues").insert(VenueCreate(weddingID:weddingID,draft:draft)).select(self.columns).single().execute().value}}
func updateVenue(id:UUID,weddingID:UUID,patch:VenuePatch)async throws->Venue{try DomainRepositorySupport.requirePatch(patch.isEmpty,"Venue update must include at least one field.");return try await run{try await self.provider.client.from("venues").update(patch).eq("id",value:DomainRepositorySupport.uuid(id)).eq("wedding_id", value: DomainRepositorySupport.uuid(weddingID)).select(self.columns).single().execute().value}}
func deleteVenue(id:UUID)async throws{let _:VenueDeleteReceipt=try await run{try await self.provider.client.from("venues").delete().eq("id",value:DomainRepositorySupport.uuid(id)).select("id").single().execute().value}}
func customColumns(weddingID: UUID) async throws -> [VenueCustomColumn] { try await run { try await self.provider.client.from("venue_custom_columns").select(self.customColumnColumns).eq("wedding_id", value: DomainRepositorySupport.uuid(weddingID)).order("position", ascending: true).execute().value } }
func createCustomColumn(_ draft: VenueCustomColumnDraft, weddingID: UUID) async throws -> VenueCustomColumn { try await run { try await self.provider.client.from("venue_custom_columns").insert(VenueCustomColumnCreate(weddingID: weddingID, draft: draft)).select(self.customColumnColumns).single().execute().value } }
func updateCustomColumn(id: UUID, weddingID: UUID, patch: VenueCustomColumnPatch) async throws -> VenueCustomColumn { try await run { try await self.provider.client.from("venue_custom_columns").update(patch).eq("id", value: DomainRepositorySupport.uuid(id)).eq("wedding_id", value: DomainRepositorySupport.uuid(weddingID)).select(self.customColumnColumns).single().execute().value } }
func deleteCustomColumn(id: UUID, weddingID: UUID) async throws { let _: VenueDeleteReceipt = try await run { try await self.provider.client.from("venue_custom_columns").delete().eq("id", value: DomainRepositorySupport.uuid(id)).eq("wedding_id", value: DomainRepositorySupport.uuid(weddingID)).select("id").single().execute().value } }
func patchCustomFields(venueID: UUID, weddingID: UUID, updates: [String: JSONValue]) async throws -> Venue { try await run { try await self.provider.client.rpc("patch_venue_custom_fields_if_planner", params: VenueCustomFieldsRPCParameters(weddingID: weddingID, venueID: venueID, updates: .object(updates))).execute().value } }
func venuePhotos(venueID:UUID)async throws->[VenuePhoto]{try await run{try await self.provider.client.from("venue_photos").select(self.photoColumns).eq("venue_id",value:DomainRepositorySupport.uuid(venueID)).order("sort_order",ascending:true,nullsFirst:false).execute().value}}
func createVenuePhoto(_ draft:VenuePhotoDraft,venueID:UUID,weddingID:UUID)async throws->VenuePhoto{try await run{try await self.provider.client.from("venue_photos").insert(VenuePhotoCreate(venueID:venueID,weddingID:weddingID,draft:draft)).select(self.photoColumns).single().execute().value}}
func updateVenuePhoto(id:UUID,patch:VenuePhotoPatch)async throws->VenuePhoto{try DomainRepositorySupport.requirePatch(patch.isEmpty,"Venue photo update must include at least one field.");return try await run{try await self.provider.client.from("venue_photos").update(patch).eq("id",value:DomainRepositorySupport.uuid(id)).select(self.photoColumns).single().execute().value}}
func deleteVenuePhoto(id:UUID)async throws{let _:VenueDeleteReceipt=try await run{try await self.provider.client.from("venue_photos").delete().eq("id",value:DomainRepositorySupport.uuid(id)).select("id").single().execute().value}}
private func run<T:Decodable & Sendable>(_ body:()async throws->T)async throws->T{do{try await DomainRepositorySupport.authenticated(provider);return try await body()}catch{throw DomainRepositorySupport.normalized(error,fallback:"Venue request failed.")}}}
private struct VenueCreate:Codable{let weddingID:UUID;let name:String;let status:VenueStatus?;let address:String?;let city:String?;let state:String?;let country:String?;let contactName:String?;let contactEmail:String?;let contactPhone:String?;let website:String?;let capacityMin:Int?;let capacityMax:Int?;let priceNotes:String?;let ourNotes:String?;let latitude:Double?;let longitude:Double?;let photoURL:String?;let customFields: JSONValue;init(weddingID:UUID,draft:VenueDraft){self.weddingID=weddingID;name=draft.name;status=draft.status;address=draft.address;city=draft.city;state=draft.state;country=draft.country;contactName=draft.contactName;contactEmail=draft.contactEmail;contactPhone=draft.contactPhone;website=draft.website;capacityMin=draft.capacityMin;capacityMax=draft.capacityMax;priceNotes=draft.priceNotes;ourNotes=draft.ourNotes;latitude=draft.latitude;longitude=draft.longitude;photoURL=draft.photoURL; customFields = draft.customFields};enum CodingKeys:String,CodingKey{case weddingID="wedding_id";case name;case status;case address;case city;case state;case country;case contactName="contact_name";case contactEmail="contact_email";case contactPhone="contact_phone";case website;case capacityMin="capacity_min";case capacityMax="capacity_max";case priceNotes="price_notes";case ourNotes="our_notes";case latitude;case longitude;case photoURL="photo_url"; case customFields = "custom_fields"}}
private struct VenueCustomColumnCreate: Codable { let weddingID: UUID; let key: String; let label: String; let kind: VenueCustomColumnKind; let options: JSONValue; let position: Int?; let hidden: Bool?; init(weddingID: UUID, draft: VenueCustomColumnDraft) { self.weddingID = weddingID; key = draft.key; label = draft.label; kind = draft.kind; options = draft.options; position = draft.position; hidden = draft.hidden }; enum CodingKeys: String, CodingKey { case weddingID = "wedding_id", key, label, kind, options, position, hidden } }
private struct VenueCustomFieldsRPCParameters: Encodable { let weddingID: UUID; let venueID: UUID; let updates: JSONValue; enum CodingKeys: String, CodingKey { case weddingID = "p_wedding_id"; case venueID = "p_venue_id"; case updates = "p_updates" } }
private struct VenuePhotoCreate:Codable{let venueID:UUID;let weddingID:UUID;let url:String;let source:String?;let caption:String?;let sortOrder:Int?;init(venueID:UUID,weddingID:UUID,draft:VenuePhotoDraft){self.venueID=venueID;self.weddingID=weddingID;url=draft.url;source=draft.source;caption=draft.caption;sortOrder=draft.sortOrder};enum CodingKeys:String,CodingKey{case venueID="venue_id";case weddingID="wedding_id";case url;case source;case caption;case sortOrder="sort_order"}}
private struct VenueDeleteReceipt:Decodable,Sendable{let id:UUID}
