import Foundation
enum WeddingTaskStatus: String, Codable, Equatable, Sendable { case backlog, todo, inProgress = "in_progress", blocked, done }
enum WeddingTaskPriority: String, Codable, Equatable, Sendable { case low, medium, high, urgent }
struct WeddingTask: Codable, Equatable, Sendable, Identifiable { let id: UUID; let weddingID: UUID; let title: String; let description: String?; let status: WeddingTaskStatus?; let priority: WeddingTaskPriority?; let ownerUserID: UUID?; let ownerLabel: String?; let dueDate: String?; let relatedVendorID: UUID?; let relatedEventID: UUID?; let createdAt: Date
    enum CodingKeys:String,CodingKey { case id;case weddingID="wedding_id";case title;case description;case status;case priority;case ownerUserID="owner_user_id";case ownerLabel="owner_label";case dueDate="due_date";case relatedVendorID="related_vendor_id";case relatedEventID="related_event_id";case createdAt="created_at" } }
struct TaskDraft: Codable, Equatable, Sendable { let title: String; let description: String?; let status: WeddingTaskStatus?; let priority: WeddingTaskPriority?; let ownerUserID: UUID?; let ownerLabel: String?; let dueDate: String?; let relatedVendorID: UUID?; let relatedEventID: UUID?
    init(title:String,description:String?=nil,status:WeddingTaskStatus?=nil,priority:WeddingTaskPriority?=nil,ownerUserID:UUID?=nil,ownerLabel:String?=nil,dueDate:String?=nil,relatedVendorID:UUID?=nil,relatedEventID:UUID?=nil){self.title=title;self.description=description;self.status=status;self.priority=priority;self.ownerUserID=ownerUserID;self.ownerLabel=ownerLabel;self.dueDate=dueDate;self.relatedVendorID=relatedVendorID;self.relatedEventID=relatedEventID}
    enum CodingKeys:String,CodingKey { case title;case description;case status;case priority;case ownerUserID="owner_user_id";case ownerLabel="owner_label";case dueDate="due_date";case relatedVendorID="related_vendor_id";case relatedEventID="related_event_id" } }
struct TaskPatch: Codable, Equatable, Sendable { let title:String?;let description:String?;let status:WeddingTaskStatus?;let priority:WeddingTaskPriority?;let ownerUserID:UUID?;let ownerLabel:String?;let dueDate:String?;let relatedVendorID:UUID?;let relatedEventID:UUID?; var isEmpty:Bool { title==nil && description==nil && status==nil && priority==nil && ownerUserID==nil && ownerLabel==nil && dueDate==nil && relatedVendorID==nil && relatedEventID==nil }
    enum CodingKeys:String,CodingKey { case title;case description;case status;case priority;case ownerUserID="owner_user_id";case ownerLabel="owner_label";case dueDate="due_date";case relatedVendorID="related_vendor_id";case relatedEventID="related_event_id" } }
