import Foundation
import Supabase
final class SupabaseScheduleRepository: ScheduleRepository, @unchecked Sendable {
    private let provider: SupabaseProvider
    private let eventColumns = "id,wedding_id,name,event_type,date,start_time,end_time,location,description,visibility,created_at"
    private let dayColumns = "id,wedding_id,time,title,description,owner,location,related_vendor_id,status,created_at"
    init(provider: SupabaseProvider) { self.provider = provider }
    func events(weddingID: UUID) async throws -> [WeddingEvent] { try await run("Schedule request failed.") { try await self.provider.client.from("events").select(self.eventColumns).eq("wedding_id", value: DomainRepositorySupport.uuid(weddingID)).order("date", ascending: true, nullsFirst: false).execute().value } }
    func createEvent(_ draft: EventDraft, weddingID: UUID) async throws -> WeddingEvent { try await run("Schedule request failed.") { try await self.provider.client.from("events").insert(EventCreate(weddingID: weddingID, draft: draft)).select(self.eventColumns).single().execute().value } }
    func updateEvent(id: UUID, patch: EventPatch) async throws -> WeddingEvent { try DomainRepositorySupport.requirePatch(patch.isEmpty, "Event update must include at least one field."); return try await run("Schedule request failed.") { try await self.provider.client.from("events").update(patch).eq("id", value: DomainRepositorySupport.uuid(id)).select(self.eventColumns).single().execute().value } }
    func deleteEvent(id: UUID) async throws { let _: DeleteReceipt = try await run("Schedule request failed.") { try await self.provider.client.from("events").delete().eq("id", value: DomainRepositorySupport.uuid(id)).select("id").single().execute().value } }
    func dayOfItems(weddingID: UUID) async throws -> [DayOfItem] { try await run("Schedule request failed.") { try await self.provider.client.from("day_of_items").select(self.dayColumns).eq("wedding_id", value: DomainRepositorySupport.uuid(weddingID)).order("time", ascending: true, nullsFirst: false).execute().value } }
    func createDayOfItem(_ draft: DayOfItemDraft, weddingID: UUID) async throws -> DayOfItem { try await run("Schedule request failed.") { try await self.provider.client.from("day_of_items").insert(DayCreate(weddingID: weddingID, draft: draft)).select(self.dayColumns).single().execute().value } }
    func updateDayOfItem(id: UUID, patch: DayOfItemPatch) async throws -> DayOfItem { try DomainRepositorySupport.requirePatch(patch.isEmpty, "Day-of-item update must include at least one field."); return try await run("Schedule request failed.") { try await self.provider.client.from("day_of_items").update(patch).eq("id", value: DomainRepositorySupport.uuid(id)).select(self.dayColumns).single().execute().value } }
    func deleteDayOfItem(id: UUID) async throws { let _: DeleteReceipt = try await run("Schedule request failed.") { try await self.provider.client.from("day_of_items").delete().eq("id", value: DomainRepositorySupport.uuid(id)).select("id").single().execute().value } }
    private func run<T: Decodable & Sendable>(_ fallback: String, _ body: () async throws -> T) async throws -> T { do { try await DomainRepositorySupport.authenticated(provider); return try await body() } catch { throw DomainRepositorySupport.normalized(error, fallback: fallback) } }
}
private struct EventCreate: Codable { let weddingID: UUID; let name: String; let eventType: EventType?; let date: String?; let startTime: String?; let endTime: String?; let location: String?; let description: String?; let visibility: EventVisibility?; init(weddingID: UUID,draft:EventDraft){self.weddingID=weddingID;name=draft.name;eventType=draft.eventType;date=draft.date;startTime=draft.startTime;endTime=draft.endTime;location=draft.location;description=draft.description;visibility=draft.visibility}; enum CodingKeys:String,CodingKey{case weddingID="wedding_id";case name;case eventType="event_type";case date;case startTime="start_time";case endTime="end_time";case location;case description;case visibility} }
private struct DayCreate: Codable { let weddingID: UUID; let time: String?; let title: String; let description: String?; let owner: String?; let location: String?; let relatedVendorID: UUID?; let status: DayOfStatus?; init(weddingID:UUID,draft:DayOfItemDraft){self.weddingID=weddingID;time=draft.time;title=draft.title;description=draft.description;owner=draft.owner;location=draft.location;relatedVendorID=draft.relatedVendorID;status=draft.status}; enum CodingKeys:String,CodingKey{case weddingID="wedding_id";case time;case title;case description;case owner;case location;case relatedVendorID="related_vendor_id";case status} }
private struct DeleteReceipt: Decodable, Sendable { let id: UUID }
