import Foundation
import Supabase
final class SupabaseBudgetRepository:BudgetRepository,@unchecked Sendable{private let provider:SupabaseProvider;private let columns="id,wedding_id,category,name,estimated_amount,actual_amount,paid_amount,status,related_vendor_id,notes,created_at";init(provider:SupabaseProvider){self.provider=provider}
func budgetItems(weddingID:UUID)async throws->[BudgetItem]{try await run{try await self.provider.client.from("budget_items").select(self.columns).eq("wedding_id",value:DomainRepositorySupport.uuid(weddingID)).order("created_at",ascending:true).execute().value}}
func createBudgetItem(_ draft:BudgetItemDraft,weddingID:UUID)async throws->BudgetItem{try await run{try await self.provider.client.from("budget_items").insert(BudgetCreate(weddingID:weddingID,draft:draft)).select(self.columns).single().execute().value}}
func updateBudgetItem(id:UUID,patch:BudgetItemPatch)async throws->BudgetItem{try DomainRepositorySupport.requirePatch(patch.isEmpty,"Budget update must include at least one field.");return try await run{try await self.provider.client.from("budget_items").update(patch).eq("id",value:DomainRepositorySupport.uuid(id)).select(self.columns).single().execute().value}}
func deleteBudgetItem(id:UUID)async throws{let _:BudgetDeleteReceipt=try await run{try await self.provider.client.from("budget_items").delete().eq("id",value:DomainRepositorySupport.uuid(id)).select("id").single().execute().value}}
private func run<T:Decodable & Sendable>(_ body:()async throws->T)async throws->T{do{try await DomainRepositorySupport.authenticated(provider);return try await body()}catch{throw DomainRepositorySupport.normalized(error,fallback:"Budget request failed.")}}}
private struct BudgetCreate:Codable{let weddingID:UUID;let category:String?;let name:String;let estimatedAmount:Double?;let actualAmount:Double?;let paidAmount:Double?;let status:BudgetStatus?;let relatedVendorID:UUID?;let notes:String?;init(weddingID:UUID,draft:BudgetItemDraft){self.weddingID=weddingID;category=draft.category;name=draft.name;estimatedAmount=draft.estimatedAmount;actualAmount=draft.actualAmount;paidAmount=draft.paidAmount;status=draft.status;relatedVendorID=draft.relatedVendorID;notes=draft.notes};enum CodingKeys:String,CodingKey{case weddingID="wedding_id";case category;case name;case estimatedAmount="estimated_amount";case actualAmount="actual_amount";case paidAmount="paid_amount";case status;case relatedVendorID="related_vendor_id";case notes}}
private struct BudgetDeleteReceipt:Decodable,Sendable{let id:UUID}
