import Foundation
enum InspirationCategory:String,Codable,Equatable,Sendable{case florals,decor,attire,venue,food,photography,stationery,beauty,other}
enum InspirationStatus:String,Codable,Equatable,Sendable{case idea,shortlisted,approved,rejected}
struct InspirationItem:Codable,Equatable,Sendable,Identifiable{let id:UUID;let weddingID:UUID;let title:String?;let imageURL:String;let sourceURL:String?;let category:InspirationCategory?;let notes:String?;let status:InspirationStatus?;let relatedVendorID:UUID?;let relatedTaskID:UUID?;let positionX:Double;let positionY:Double;let width:Double;let createdAt:Date;let updatedAt:Date
enum CodingKeys:String,CodingKey{case id;case weddingID="weddingId";case title;case imageURL="imageUrl";case sourceURL="sourceUrl";case category;case notes;case status;case relatedVendorID="relatedVendorId";case relatedTaskID="relatedTaskId";case positionX;case positionY;case width;case createdAt;case updatedAt}}
struct InspirationDraft:Codable,Equatable,Sendable{let title:String?;let imageURL:String;let sourceURL:String?;let category:InspirationCategory?;let notes:String?;let status:InspirationStatus?;let relatedVendorID:UUID?;let relatedTaskID:UUID?;let positionX:Double?;let positionY:Double?;let width:Double?;enum CodingKeys:String,CodingKey{case title;case imageURL="image_url";case sourceURL="source_url";case category;case notes;case status;case relatedVendorID="related_vendor_id";case relatedTaskID="related_task_id";case positionX="position_x";case positionY="position_y";case width}}
struct InspirationPatch:Codable,Equatable,Sendable{let title:String?;let imageURL:String?;let sourceURL:String?;let category:InspirationCategory?;let notes:String?;let status:InspirationStatus?;let relatedVendorID:UUID?;let relatedTaskID:UUID?;let positionX:Double?;let positionY:Double?;let width:Double?;var isEmpty:Bool{title==nil&&imageURL==nil&&sourceURL==nil&&category==nil&&notes==nil&&status==nil&&relatedVendorID==nil&&relatedTaskID==nil&&positionX==nil&&positionY==nil&&width==nil};enum CodingKeys:String,CodingKey{case title;case imageURL="image_url";case sourceURL="source_url";case category;case notes;case status;case relatedVendorID="related_vendor_id";case relatedTaskID="related_task_id";case positionX="position_x";case positionY="position_y";case width}}
struct MoodboardRequirement:Codable,Equatable,Sendable,Identifiable{let id:UUID;let weddingID:UUID;let importance:String;let title:String;let description:String?;let position:Int;let createdAt:Date;let updatedAt:Date;enum CodingKeys:String,CodingKey{case id;case weddingID="weddingId";case importance;case title;case description;case position;case createdAt;case updatedAt}}
struct MoodboardNote:Codable,Equatable,Sendable,Identifiable{let id:UUID;let weddingID:UUID;let title:String;let body:String;let positionX:Double;let positionY:Double;let width:Double;let height:Double;let createdAt:Date;let updatedAt:Date;enum CodingKeys:String,CodingKey{case id;case weddingID="weddingId";case title;case body;case positionX;case positionY;case width;case height;case createdAt;case updatedAt}}
