import Foundation
import Supabase
final class SupabaseInspirationRepository:InspirationRepository,@unchecked Sendable{private let provider:SupabaseProvider;private let columns="id,wedding_id,title,image_url,source_url,notes,position_x,position_y,width,created_at,updated_at";init(provider:SupabaseProvider){self.provider=provider}
func inspirationItems(weddingID:UUID)async throws->[InspirationItem]{try await run{try await self.provider.client.from("inspiration_items").select(self.columns).eq("wedding_id",value:DomainRepositorySupport.uuid(weddingID)).order("updated_at",ascending:true).execute().value}}
func createInspirationItem(_ draft:InspirationDraft,weddingID:UUID)async throws->InspirationItem{try await run{try await self.provider.client.from("inspiration_items").insert(InspirationCreate(weddingID:weddingID,draft:draft)).select(self.columns).single().execute().value}}
func updateInspirationItem(id:UUID,patch:InspirationPatch)async throws->InspirationItem{try DomainRepositorySupport.requirePatch(patch.isEmpty,"Inspiration update must include at least one field.");return try await run{try await self.provider.client.from("inspiration_items").update(patch).eq("id",value:DomainRepositorySupport.uuid(id)).select(self.columns).single().execute().value}}
func deleteInspirationItem(id:UUID)async throws{let _:InspirationDeleteReceipt=try await run{try await self.provider.client.from("inspiration_items").delete().eq("id",value:DomainRepositorySupport.uuid(id)).select("id").single().execute().value}}
func moodboardRequirements(weddingID:UUID)async throws->[MoodboardRequirement]{try await run{try await self.provider.client.from("moodboard_requirements").select("id,wedding_id,importance,title,description,position,created_at,updated_at").eq("wedding_id",value:DomainRepositorySupport.uuid(weddingID)).order("position",ascending:true).order("created_at",ascending:true).execute().value}}
func createMoodboardRequirement(_ draft:MoodboardRequirementDraft,weddingID:UUID)async throws->MoodboardRequirement{try await run{try await self.provider.client.from("moodboard_requirements").insert(MoodboardRequirementCreate(weddingID:weddingID,draft:draft)).select("id,wedding_id,importance,title,description,position,created_at,updated_at").single().execute().value}}
func moodboardNotes(weddingID:UUID)async throws->[MoodboardNote]{try await run{try await self.provider.client.from("moodboard_notes").select("id,wedding_id,title,body,position_x,position_y,width,height,created_at,updated_at").eq("wedding_id",value:DomainRepositorySupport.uuid(weddingID)).order("updated_at",ascending:true).execute().value}}
private func run<T:Decodable & Sendable>(_ body:()async throws->T)async throws->T{do{try await DomainRepositorySupport.authenticated(provider);return try await body()}catch{throw DomainRepositorySupport.normalized(error,fallback:"Inspiration request failed.")}}}
private struct InspirationCreate:Codable{let weddingID:UUID;let title:String?;let imageURL:String;let sourceURL:String?;let notes:String?;let positionX:Double?;let positionY:Double?;let width:Double?;init(weddingID:UUID,draft:InspirationDraft){self.weddingID=weddingID;title=draft.title;imageURL=draft.imageURL;sourceURL=draft.sourceURL;notes=draft.notes;positionX=draft.positionX;positionY=draft.positionY;width=draft.width};enum CodingKeys:String,CodingKey{case weddingID="wedding_id";case title;case imageURL="image_url";case sourceURL="source_url";case notes;case positionX="position_x";case positionY="position_y";case width}}
private struct MoodboardRequirementCreate:Codable{let weddingID:UUID;let importance:String;let title:String;let description:String?;let position:Int;init(weddingID:UUID,draft:MoodboardRequirementDraft){self.weddingID=weddingID;importance=draft.importance;title=draft.title;description=draft.description;position=draft.position};enum CodingKeys:String,CodingKey{case weddingID="wedding_id";case importance;case title;case description;case position}}
private struct InspirationDeleteReceipt:Decodable,Sendable{let id:UUID}
