import Foundation
enum VendorCategory: String, Codable, Equatable, Sendable { case venue, catering, photography, videography, florist, music, beauty, attire, stationery, transportation, hotel, officiant, decor, cake, other }
enum VendorStatus: String, Codable, Equatable, Sendable { case researching, contacted, quoteReceived = "quote_received", shortlisted, booked, rejected }
struct Vendor: Codable, Equatable, Sendable, Identifiable { let id:UUID;let weddingID:UUID;let name:String;let category:VendorCategory?;let contactName:String?;let email:String?;let phone:String?;let website:String?;let status:VendorStatus?;let quotedAmount:Double?;let finalAmount:Double?;let depositAmount:Double?;let amountPaid:Double?;let nextPaymentDueDate:String?;let notes:String?;let rating:Int?;let createdAt:Date
enum CodingKeys:String,CodingKey{case id;case weddingID="wedding_id";case name;case category;case contactName="contact_name";case email;case phone;case website;case status;case quotedAmount="quoted_amount";case finalAmount="final_amount";case depositAmount="deposit_amount";case amountPaid="amount_paid";case nextPaymentDueDate="next_payment_due_date";case notes;case rating;case createdAt="created_at"}}
struct VendorDraft: Codable, Equatable, Sendable { let name:String;let category:VendorCategory?;let contactName:String?;let email:String?;let phone:String?;let website:String?;let status:VendorStatus?;let quotedAmount:Double?;let finalAmount:Double?;let depositAmount:Double?;let amountPaid:Double?;let nextPaymentDueDate:String?;let notes:String?;let rating:Int?
enum CodingKeys:String,CodingKey{case name;case category;case contactName="contact_name";case email;case phone;case website;case status;case quotedAmount="quoted_amount";case finalAmount="final_amount";case depositAmount="deposit_amount";case amountPaid="amount_paid";case nextPaymentDueDate="next_payment_due_date";case notes;case rating}}
struct VendorPatch: Codable, Equatable, Sendable { let name:String?;let category:VendorCategory?;let contactName:String?;let email:String?;let phone:String?;let website:String?;let status:VendorStatus?;let quotedAmount:Double?;let finalAmount:Double?;let depositAmount:Double?;let amountPaid:Double?;let nextPaymentDueDate:String?;let notes:String?;let rating:Int?;var isEmpty:Bool{name==nil&&category==nil&&contactName==nil&&email==nil&&phone==nil&&website==nil&&status==nil&&quotedAmount==nil&&finalAmount==nil&&depositAmount==nil&&amountPaid==nil&&nextPaymentDueDate==nil&&notes==nil&&rating==nil}
enum CodingKeys:String,CodingKey{case name;case category;case contactName="contact_name";case email;case phone;case website;case status;case quotedAmount="quoted_amount";case finalAmount="final_amount";case depositAmount="deposit_amount";case amountPaid="amount_paid";case nextPaymentDueDate="next_payment_due_date";case notes;case rating}}
